name: whats_pie
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.5
  path: ^1.9.0
  either_dart: ^1.0.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  collection: ^1.18.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.2.1
  resizable_widget: ^1.0.5
  intl:
  huge_listview: ^2.0.12
  scrollable_positioned_list: ^0.3.8
  shimmer: ^3.0.0
  syncfusion_flutter_pdfviewer: ^26.1.40
  ogg_opus_player: ^0.7.0
  media_kit: ^1.1.10                             # Primary package.
  media_kit_video: ^1.2.4                        # For video rendering.
  media_kit_libs_video: ^1.0.4                   # Native video dependencies.
  url_launcher: ^6.3.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/app_icon.png